name = input('Please enter your name')
matnum = input('Please enter your Matric Number')
classs = input('Please enter your Classs')
phonenum = input('Please enter your Number')

print('******************************************')
print('*        MY PERSONAL INFORMATION         *')
print('******************************************')
print('NAME           : ',name)
print('MATRIC NUMBER  : ',matnum)
print('CLASS          : '+classs)
print('PHONE NUMBER   : '+phonenum)